apiVersion: v1
kind: Pod
metadata:
  name: mandlebrot-c-podman-wasm-pod
  annotations:
    module.wasm.image/variant: compat-smart
spec:
  containers:
    - name: container
      image: mandlebrot-c-podman-wasm
